# Uncomment this line to define a global platform for your project
 platform :osx, '10.12'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'iStockcheck' do
	pod 'Alamofire', '~> 4.0'
	pod 'SwiftyJSON', '~> 3.1'
end

