# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='iPhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AppleStore')),
                ('iphone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.iPhoneModel')),
            ],
        ),
    ]
