# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170811_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='apple_store',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='iphone_model',
        ),
        migrations.AddField(
            model_name='applestore',
            name='models_in_stock',
            field=models.ManyToManyField(to='main.IphoneModel'),
        ),
        migrations.AddField(
            model_name='applestore',
            name='updated_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
